"""initial schema

Revision ID: b168a0d39e08
Revises: 
Create Date: 2026-02-12 21:22:00.550591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b168a0d39e08'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('passwordHash', sa.String(), nullable=False),
    sa.Column('bikeName', sa.String(length=100), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('userId'),
    sa.UniqueConstraint('username')
    )
    op.create_table('rides',
    sa.Column('rideId', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hostId', sa.UUID(), nullable=False),
    sa.Column('rideName', sa.String(length=150), nullable=False),
    sa.Column('rideStartTime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rideStartPoint', sa.String(length=255), nullable=False),
    sa.Column('rideEndPoint', sa.String(length=255), nullable=False),
    sa.Column('rideDuration', sa.Float(), nullable=True),
    sa.Column('haltDuration', sa.Float(), nullable=True),
    sa.Column('routeLink', sa.String(), nullable=False),
    sa.Column('maxParticipants', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('UPCOMING', 'ONGOING', 'COMPLETED', 'CANCELLED', name='ride_status'), nullable=False),
    sa.ForeignKeyConstraint(['hostId'], ['users.userId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rideId')
    )
    op.create_index(op.f('ix_rides_rideStartTime'), 'rides', ['rideStartTime'], unique=False)
    op.create_index(op.f('ix_rides_status'), 'rides', ['status'], unique=False)
    op.create_table('comments',
    sa.Column('commentId', sa.UUID(), nullable=False),
    sa.Column('rideId', sa.UUID(), nullable=False),
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('commentText', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rideId'], ['rides.rideId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('commentId')
    )
    op.create_index(op.f('ix_comments_rideId'), 'comments', ['rideId'], unique=False)
    op.create_index(op.f('ix_comments_userId'), 'comments', ['userId'], unique=False)
    op.create_table('ride_participants',
    sa.Column('rideId', sa.UUID(), nullable=False),
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='participant_status'), nullable=False),
    sa.Column('requestedAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decisionAt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['rideId'], ['rides.rideId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rideId', 'userId')
    )
    op.create_index(op.f('ix_ride_participants_status'), 'ride_participants', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ride_participants_status'), table_name='ride_participants')
    op.drop_table('ride_participants')
    op.drop_index(op.f('ix_comments_userId'), table_name='comments')
    op.drop_index(op.f('ix_comments_rideId'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_rides_status'), table_name='rides')
    op.drop_index(op.f('ix_rides_rideStartTime'), table_name='rides')
    op.drop_table('rides')
    op.drop_table('users')
    # ### end Alembic commands ###
